### ISSUE TITLE
(with haskell-stack) $HOME/.cabal/packages/hackage.haskell.org/00-index.tar: openBinaryFile: does not exist (No such file or directory)

### ISSUE THREAD

**Issue by aiya000** [y-taka-23/thank-you-stars#1]
Hi, I want to use this great project :smile:

but I got

```console
$ cd {my-project}
$ thank-you-stars
{my-project}: /home/aiya000/.cabal/packages/hackage.haskell.org/00-index.tar: openBinaryFile: does not exist (No such file or directory)
```

Also

```console
$ ls ~/.cabal
config
```

What is `.cabal/packages/hackage.haskell.org/00-index.tar` :thinking: ?

**Comment by y-taka-23** [comment]
Thanks a lot for your report.

It's a sort of bugs. The tool fetches not Stack's package indices but Cabal's, therefore, cannot go if you have't installed Cabal on your machine. I'm working to fix the problem...

Anyway, could you try the following as a workaround?

```console
$ ln -s $HOME/.stack/indices/Hackage/00-index.tar $HOME/.cabal/packages/hackage.haskell.org/00-index.tar
$ cd {your-project}
$ thank-you-stars
```

**Comment by aiya000** [comment]
The workaround works well, thanks 👍 👍

**Comment by aiya000** [comment]
The workaround works well, thanks 👍 👍

**Comment by y-taka-23** [comment]
FYI: fixed the code: https://github.com/y-taka-23/thank-you-stars/commit/bab0f955f28b2a348111ff5090fdbf3166b239e0

**Comment by aiya000** [comment]
@y-taka-23 It works on my environment too, thx!

**Comment by epicallan** [comment]
Hi @aiya000 , I am having a similar issue
```
thank-you-stars: cannot parse cabal package "QuickCheck"-2.11.3: FromString "unexpected '{'" (Just 1)
CallStack (from HasCallStack):
  error, called at src/Distribution/Hackage/DB/Parsed.hs:65:40 in hackage-db-1.22-C8GnEWlJlvn9TtHrPL8f8i:Distribution.Hackage.DB.Parsed
```
