### ISSUE TITLE
Blacklist repositories

### ISSUE THREAD

**Issue by hasufell** [y-taka-23/thank-you-stars#5]
Hey, is there a way to blacklist repositories from being starred?

E.g. https://github.com/vincenthz/hs-tls is known to not have mitigated certain timing attacks and is generally very controversial to the point that I don't want to run it in production, advise against its use and don't want it to be starred.

So this isn't really about trolling, but actual concerns.

**Comment by y-taka-23** [comment]
Sorry but I have no plan to implement such a function.
